name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or stack trace
      description: |
        Please copy and paste any relevant log output.
        Add the full stack trace if available.
        
        *This will be automatically formatted into code, so there is no need for backticks.*
      render: shell

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows

  - type: checkboxes
    id: version
    attributes:
      label: Plugin version
      options:
        - label: I'm using the latest plugin version or believe the bug exists in it.
          required: true
