name: Build Assets

on:
  push:
    branches:
      - master
    paths:
      - generate/**
      - .github/workflows/build-assets.yml
      - builder.json
      - package.json
      - bun.lock
      - tsconfig.json
  pull_request:
    paths:
      - generate/**
      - .github/workflows/build-assets.yml
      - builder.json
      - package.json
      - bun.lock
      - tsconfig.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-assets:
    name: Build Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Start Builder
        run: bun run start

      - name: Archive production artifacts
        uses: actions/upload-artifact@v7
        with:
          name: assets
          path: assets-dist/

  deploy:
    name: Upload to S3
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-slim
    needs: build-assets

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: assets
          path: assets-dist/

      - name: Upload files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        run: |
          aws configure set region auto
          aws s3 sync --endpoint-url $AWS_ENDPOINT assets-dist/ s3://cat-activity
