name: Preview Build Assets

on:
  pull_request:
    branches:
      - master
    paths:
      - 'generate/**'
      - '.github/workflows/icons.yml'
      - 'builder_config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

permissions:
  contents: read

jobs:
  build-builder:
    name: Build Assets builder
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dev Dependencies
        run: npm ci --save-dev

      - name: Build Project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  build-assets:
    name: (Not) Build Assets
    runs-on: ubuntu-24.04-arm
    needs: build-builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Install Dependencies
        run: npm ci --omit=dev

      - name: Start Builder
        run: npm run start-without-build