name: Publish Plugin

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.1.1"
          cache-read-only: false

      - name: Add the secret files
        run: |
          mkdir -p ./token
          echo "${{ secrets.CHAIN_CRT_CONTENTS }}" > ./token/chain.crt
          echo "${{ secrets.PRIVATE_PEM_CONTENTS }}" > ./token/private.pem

      - name: Build plugin
        run: gradle buildPlugin
        env:
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Sign plugin
        run: gradle signPlugin
        env:
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

      - name: Publish plugin
        run: gradle publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
